import { GameConfig, GameType } from '@/lib/types';

export const GAMES: Record<GameType, GameConfig> = {
  'beer-pressure': {
    id: 'beer-pressure',
    name: 'Beer Pressure',
    tagline: 'Cards · 2–10 players',
    blurb: 'Turn-based prompts. Three rules in play at once.',
    icon: 'Beer',
    gradient: 'from-amber-500 to-orange-600',
    accent: 'var(--game-beer-pressure)',
    num: '01',
    phase: 1,
    supportsSpice: true,
    supportsTheme: true,
  },
  'truth-or-drink': {
    id: 'truth-or-drink',
    name: 'Truth or Drink',
    tagline: 'Confess · 2–8 players',
    blurb: 'Reveal the answer. Or skip and sip.',
    icon: 'MessageCircle',
    gradient: 'from-pink-500 to-rose-600',
    accent: 'var(--game-truth-or-drink)',
    num: '02',
    phase: 1,
    supportsSpice: true,
    supportsTheme: true,
  },
  'id-game': {
    id: 'id-game',
    name: 'The ID Game',
    tagline: 'Heads up · 3+ players',
    blurb: 'A word on your forehead. Sixty seconds.',
    icon: 'Smartphone',
    gradient: 'from-blue-500 to-indigo-600',
    accent: 'var(--game-id-game)',
    num: '03',
    phase: 1,
    supportsSpice: false,
    supportsTheme: true,
  },
  'kings-cup': {
    id: 'kings-cup',
    name: "King's Cup",
    tagline: 'Classic · 4+ players',
    blurb: 'Fifty-two cards. Fifty-two consequences.',
    icon: 'Crown',
    gradient: 'from-purple-500 to-violet-600',
    accent: 'var(--game-kings-cup)',
    num: '04',
    phase: 1,
    supportsSpice: false,
    supportsTheme: false,
  },
  'most-likely-to': {
    id: 'most-likely-to',
    name: 'Most Likely To',
    tagline: 'Pointing · 4+ players',
    blurb: 'Point at who fits. Most fingers drinks.',
    icon: 'Users',
    gradient: 'from-green-500 to-emerald-600',
    accent: 'var(--game-most-likely)',
    num: '05',
    phase: 1,
    supportsSpice: true,
    supportsTheme: true,
  },
  'never-have-i-ever': {
    id: 'never-have-i-ever',
    name: 'Never Have I Ever',
    tagline: 'Confess · 3+ players',
    blurb: 'Ten fingers up. Watch them fall.',
    icon: 'Hand',
    gradient: 'from-red-500 to-rose-600',
    accent: 'var(--game-never)',
    num: '06',
    phase: 1,
    supportsSpice: true,
    supportsTheme: true,
  },
  'categories': {
    id: 'categories',
    name: 'Categories',
    tagline: 'Speed · 3+ players',
    blurb: 'Name them. Quickly. Don\'t freeze.',
    icon: 'List',
    gradient: 'from-cyan-500 to-teal-600',
    accent: 'var(--game-categories)',
    num: '07',
    phase: 1,
    supportsSpice: false,
    supportsTheme: true,
  },
  'paranoia': {
    id: 'paranoia',
    name: 'Paranoia',
    tagline: 'Whisper · 4+ players',
    blurb: 'Whisper, flip, reveal.',
    icon: 'Eye',
    gradient: 'from-slate-500 to-zinc-600',
    accent: 'var(--muted)',
    num: '08',
    phase: 2,
    supportsSpice: true,
    supportsTheme: true,
  },
  'power-hour': {
    id: 'power-hour',
    name: 'Power Hour',
    tagline: 'Timer · 2+ players',
    blurb: '60 minutes, 60 sips.',
    icon: 'Timer',
    gradient: 'from-yellow-500 to-amber-600',
    accent: 'var(--copper)',
    num: '09',
    phase: 3,
    supportsSpice: false,
    supportsTheme: false,
  },
  'movie-mode': {
    id: 'movie-mode',
    name: 'Movie Mode',
    tagline: 'Watch · 2+ players',
    blurb: 'AI-generated drinking rules for any film.',
    icon: 'Film',
    gradient: 'from-fuchsia-500 to-purple-600',
    accent: 'var(--burgundy)',
    num: '10',
    phase: 2,
    supportsSpice: false,
    supportsTheme: true,
  },
};

export const PHASE_1_GAMES = Object.values(GAMES).filter((g) => g.phase === 1);
export const PHASE_2_GAMES = Object.values(GAMES).filter((g) => g.phase === 2);
export const PHASE_3_GAMES = Object.values(GAMES).filter((g) => g.phase === 3);
export const ALL_GAMES = Object.values(GAMES);

export function getGameConfig(gameType: GameType): GameConfig {
  return GAMES[gameType];
}
